name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

# One or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build for deployment
    runs-on: ubuntu-latest
    steps:
      # Check-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      # Build, copy `build` folder contents into `docs` folder for GitHub Pages, and commit
      - run: |
          npm install
          npm run build
          cp -r build/ docs/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Build for deployment'
          git push
